### ISSUE TITLE
I propose instead of trying to understand the protocol. We see if we can just download the server software directly from a server. Not resorting to anything illegal.

### ISSUE THREAD

**Issue by Colonizor48** [firebolt55439/Diep.io-Protocol#47]
Title. It could be possible to just download the server directly.

**Comment by Colonizor48** [comment]
If they forgot security entirely. We could see what server the game connects to. Then use a fuzzler to discover any directories and then download any files in those directories. It probably wont work but if it does we have 85% of our work done.

**Comment by Colonizor48** [comment]
https://diepio.fandom.com/wiki/Alpha_Pentagon
"Trivia

A clear image of an Alpha Pentagon.

    It was believed for long that Alpha Pentagon has 2,000 HP, but tests showed that it has approximately 1,071 HP (or 3,000 HP if you convert the value into the current metric system), and recently it was confirmed that the Alpha Pentagon has 3,000 HP (by using the developer tools), which is the same HP as all of the Bosses in the game. The Alpha Pentagon has less body damage, though." What are these developer tools and can we access them?

**Comment by Colonizor48** [comment]
Be warned. If you go searching for dev mode you will likly only find clickbate and computer generated nonsense. But who knows. Perhapse deep enough in google there is a way.

**Comment by Colonizor48** [comment]
https://github.com/HueHanaejistla/diep.io-protocol-wiki This may be of great use. https://github.com/rafern/diep.io-wasm-re This aswell.

**Comment by FlorianCassayre** [comment]
I don't participate in this project anymore (not that I don't like it, because I do, just don't have the time) - however by reading your comments it really sounds like you're encouraging to commit something illegal. While it may be possible to obtain some clues about the original sources that way, it's in my opinion highly unlikely and not worth the risk.
If you're wondering about the obfuscated JS, it has been automatically synthesized by Emscripten. Or at least that's how it used to be. Even with advanced tools it's _very_ painful to analyze, which explains the choice to resort to network sniffing. The projects you mentioned are promising as they seem to have gone farther than we did, before going unmaintained.

Edit: Not to demotivate you but Matheus (the creator) hates when people look into things they shouldn't be looking into. I'm sure he invests a significant amount of energy in preventing the game from being modded and keeping the bots away.

**Comment by Colonizor48** [comment]
Yeah dont do this this isn't good. Im closing this.
